### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by payload3r** [Prepouce/CoercedPotato#7]
Hello!

Could you please help me to understand what Im doing wrong when I try to compile this project? I'm getting the following errors:

![errors](https://github.com/user-attachments/assets/ee50b306-5917-4fcf-a791-1762f9eaa95f)

This is how I downloaded the project (just to confirm that the submodule is there):

```bash
git clone --recurse-submodules https://github.com/Prepouce/CoercedPotato.git
```

The required files exist, but for some reason VS doesn't like it:

![errors2](https://github.com/user-attachments/assets/95c1a684-4c44-442d-950b-30138d93fd67)

![errors4](https://github.com/user-attachments/assets/392d69b4-1636-4692-aafd-3bcfeaa49ee1)

![errors3](https://github.com/user-attachments/assets/4f8b543c-b91a-40d8-92bf-d9f00e7b450f)

**Comment by Prepouce** [comment]
Hello mate ! Thanks for the issue :D. We will investigate this strange error ... 

Meanwhile, I have updated the "readme" file, to give a temporary fix: 

![image](https://github.com/user-attachments/assets/70de5be4-5db2-4b1e-af95-184bdf91b43e)
